// CRYPTO
export const GET_CRYPTO_LIST = 'GET_CRYPTO_LIST';
export const GET_CRYPTO_DATA = 'GET_CRYPTO_DATA';
export const GET_CRYPTO_HISTORY = 'GET_CRYPTO_HISTORY';
export const SORT_CRYPTO_DATA = 'SORT_CRYPTO_DATA';
export const SEARCH_CRYPTO_DATA = 'SEARCH_CRYPTO_DATA';
export const GET_CRYPTO_FAVORITES = 'GET_CRYPTO_FAVORITES';

// AUTHENTICATION
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';